services:
  db:
    image: postgres
    restart: always
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./.db:/var/lib/postgresql/data
